#!/bin/bash

flex calc-lexico.l 
bison -d calc-sintaxis.y
gcc lex.yy.c calc-sintaxis.tab.c
gcc lex.yy.c calc-sintaxis.tab.c tree_builder.c
gcc lex.yy.c calc-sintaxis.tab.c tree_builder.c -o parser -lfl      <-
./parser < input.txt